name: Auto Reviewers

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: ".github/auto_assign.yml"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      