name: Auto Label PR by Title Prefix

on:
  pull_request:
    types: [opened, edited] # PR이 열리거나 제목이 수정되었을 때 실행

permissions:
  contents: read          # 코드는 읽기만 필요
  pull-requests: write    # PR에 라벨을 추가하기 위한 쓰기 권한
  issues: read            # 저장소 라벨 목록을 읽기 위한 권한 (필요할 수 있음)

jobs:
  add-chapter-label:
    runs-on: ubuntu-latest
    # PR 제목에서 [n장] 패턴을 확인하고, 'n장'으로 시작하는 기존 라벨을 찾아 추가합니다.
    steps:
      - name: Extract chapter prefix and add matching label
        uses: actions/github-script@v7 # 또는 최신 버전
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const prNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // PR 제목 시작 부분에서 '[숫자장]' 패턴을 찾습니다.
            const match = prTitle.match(/^\[(\d+장)\]/);

            if (match && match[1]) {
              const prefix = match[1]; // 예: '1장', '10장'
              console.log(`Found chapter prefix: "${prefix}" in PR title: "${prTitle}"`);

              let foundLabelName = null;

              try {
                // 저장소의 모든 라벨 목록을 가져옵니다.
                // 참고: 라벨이 매우 많으면 pagination 처리가 필요할 수 있습니다.
                const { data: repoLabels } = await github.rest.issues.listLabelsForRepo({
                  owner,
                  repo,
                  per_page: 100 // 한 페이지에 가져올 라벨 수 (기본 30, 최대 100)
                });

                // 가져온 라벨 목록에서 prefix로 시작하는 라벨을 찾습니다.
                for (const label of repoLabels) {
                  if (label.name.startsWith(prefix)) {
                    foundLabelName = label.name; // 예: '1장 들어가며'
                    console.log(`Found matching label: "${foundLabelName}"`);
                    break; // 첫 번째 매칭되는 라벨을 찾으면 중단
                  }
                }

                if (foundLabelName) {
                  // 찾은 라벨을 PR에 추가합니다.
                  await github.rest.issues.addLabels({
                    owner,
                    repo,
                    issue_number: prNumber,
                    labels: [foundLabelName] // 찾은 전체 라벨 이름 사용
                  });
                  console.log(`Successfully added label "${foundLabelName}" to PR #${prNumber}`);
                } else {
                  console.log(`No existing label found starting with "${prefix}"`);
                }

              } catch (error) {
                console.error(`Error processing labels for PR #${prNumber}. Error: ${error.message}`);
                // 라벨 목록 조회 실패 또는 라벨 추가 실패 시 오류 로깅
              }
            } else {
              console.log(`No chapter prefix like '[n장]' found in PR title: "${prTitle}"`);
            }